# Use the official PHP image with FPM
FROM php:fpm

# Add PostgreSQL APT repository to install the correct version of the PostgreSQL client
RUN apt-get update -y \
    && apt-get install -y wget gnupg2 lsb-release \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && apt-get update -y

# Install the required dependencies, including PostgreSQL client 16
RUN apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libyaml-dev \
    libzip-dev \
    libpq-dev \
    postgresql-client-16

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo pdo_pgsql zip  # Install pdo_pgsql for PostgreSQL

# Install YAML extension
RUN pecl install yaml \
    && docker-php-ext-enable yaml

# Clear apt cache to reduce image size
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
