version: "3"

services:
  php:
    build: ./docker/php
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
    depends_on:
      - postgres
    networks:
      - internal

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
