
/:
  controller: Home
  action: index

# Installer routes
/installer:
  controller: Installer
  action: index

/installer/process:
  controller: Installer
  action: configDatabase

/installer/account:
  controller: Installer
  action: createAdmin

/installer/validate:
  controller: Security
  action: validate

/installer/login:
  controller: Security
  action: login

/installer/forgot-password:
  controller: Security
  action: forgotPassword

# dashboard routes

/dashboard:
  controller: Dashboard
  action: index

/dashboard/page-builder:
  controller: Dashboard
  action: index

/dashboard/article:
  controller: Dashboard
  action: index

/dashboard/page-builder/delete-page:
  controller: PageBuilder
  action: deletePage

/dashboard/create-article:
  controller: Dashboard
  action: index

/dashboard/article/create:
  controller: Article
  action: save

/dashboard/delete-article:
  controller: Article
  action: delete

/dashboard/article/block:
  controller: Article
  action: getArticlesJson

/dashboard/article/save-comment:
  controller: Comment
  action: save

/dashboard/update-article:
  controller: Dashboard
  action: index

/dashboard/page-builder/create-page:
  controller: Dashboard
  action: index

/dashboard/page-builder/create-page/save:
  controller: PageBuilder
  action: savePage

/dashboard/page-builder/update-page:
  controller: PageBuilder
  action: updatePage

/dashboard/chart:
  controller: Dashboard
  action: index

/dashboard/comment:
  controller: Dashboard
  action: index

/dashboard/comment/delete:
  controller: Comment
  action: delete

/dashboard/comment/approve:
  controller: Comment
  action: approve

/dashboard/user:
  controller: Dashboard
  action: index

/dashboard/logout:
  controller: Security
  action: logout

/dashboard/update-password:
  controller: Security
  action: changePassword

/dashboard/update-user:
  controller: User
  action: editUser

/dashboard/list-users:
  controller: Dashboard
  action: index

/dashboard/update-role:
  controller: User
  action: updateRole

/dashboard/soft-delete:
  controller: User
  action: softDelete

/dashboard/hard-delete:
  controller: User
  action: hardDelete

/dashboard/delete-user:
  controller: User
  action: delete

# User routes

/user/login:
  controller: Security
  action: login

/user/register:
  controller: Security
  action: register

/user/validate:
  controller: Security
  action: validate

/user/forgot-password:
  controller: Security
  action: forgotPassword

/user/reset-password:
  controller : Security
  action: changePassword

/user/comment:
  controller: Comment
  action: create